#ifndef EVENT_H
#define EVENT_H

enum class Event {
    WINDOW_CLOSE,
    PROGRAM_EXIT,
    
    CAMERA_MOVE_LEFT,
    CAMERA_MOVE_RIGHT,
    CAMERA_MOVE_FORWARDS,
    CAMERA_MOVE_BACKWARDS,
    CAMERA_ROTATE_LEFT,
    CAMERA_ROTATE_RIGHT,
    CAMERA_ROTATE_UP,
    CAMERA_ROTATE_DOWN,
    CAMERA_ROTATE_ROLL_LEFT,
    CAMERA_ROTATE_ROLL_RIGHT,

    RUBIK_ROTATE_RIGHT,
    RUBIK_ROTATE_RIGHT_INV,
    RUBIK_ROTATE_LEFT,
    RUBIK_ROTATE_LEFT_INV,
    RUBIK_ROTATE_UP,
    RUBIK_ROTATE_UP_INV,
    RUBIK_ROTATE_BOTTOM,
    RUBIK_ROTATE_BOTTOM_INV,
    RUBIK_ROTATE_FRONT,
    RUBIK_ROTATE_FRONT_INV,
    RUBIK_ROTATE_BACK,
    RUBIK_ROTATE_BACK_INV,
};

#endif